"""Grade a submission against a competition's private answers.

Mirrors upstream MLE-bench's grading contract so results mean the same thing:
a report distinguishes *no submission* from *a submission that could not be
graded* from *a graded score*, and medal thresholds come from rank positions on
a leaderboard using upstream's exact tier rules.

One deliberate divergence, and it is an improvement. Upstream reads a raw score
value at a rank position on the *original Kaggle leaderboard*, which was
computed on Kaggle's private split, and compares it against a score computed on
MLE-bench's own re-split. Of upstream's 82 preparation scripts, 69 use a plain
i.i.d. ``train_test_split`` with no stratification and no group- or time-awareness,
while the Kaggle private splits those thresholds came from were often split by
time, site or patient deliberately. An i.i.d. split is systematically easier, so
the transfer is biased upward rather than merely noisy.

For a competition generated by :mod:`mlea.bench`, the leaderboard is computed on
**the same split the agent is graded on**, so that bias is zero by construction.
"""

from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Sequence

import numpy as np

from .metrics import InvalidSubmission, get_metric


#: Upstream rounds every graded score to this many decimals before comparing it
#: against medal thresholds (``mlebench/grade_helpers.py::Grader.__call__``).
UPSTREAM_SCORE_DECIMALS = 5


@dataclass(frozen=True)
class MedalThresholds:
    """Score values at the gold/silver/bronze rank positions."""

    gold: float
    silver: float
    bronze: float
    median: float
    n_teams: int

    def beats(self, score: float, greater_is_better: bool, threshold: float) -> bool:
        return score >= threshold if greater_is_better else score <= threshold


def medal_ranks(n_teams: int) -> tuple[int, int, int]:
    """Gold/silver/bronze rank positions, 1-indexed.

    Upstream's tiers verbatim (``mlebench/grade_helpers.py::rank_score``),
    which follow kaggle.com/progression:

    * 1-99 teams:    gold = ``int(N*0.1)``, silver = ``int(N*0.2)``, bronze = ``int(N*0.4)``
    * 100-249:       gold = 10, silver = 20, bronze = ``int(N*0.4)``
    * 250-999:       gold = ``10 + int(N*0.002)``, silver = 50, bronze = 100
    * >=1000:        gold = ``10 + int(N*0.002)``, silver = ``int(N*0.05)``, bronze = ``int(N*0.1)``
    """
    if n_teams < 1:
        raise ValueError("a leaderboard needs at least one team")
    if n_teams < 100:
        g, s, b = int(n_teams * 0.1), int(n_teams * 0.2), int(n_teams * 0.4)
    elif n_teams < 250:
        g, s, b = 10, 20, int(n_teams * 0.4)
    elif n_teams < 1000:
        g, s, b = 10 + int(n_teams * 0.002), 50, 100
    else:
        g, s, b = 10 + int(n_teams * 0.002), int(n_teams * 0.05), int(n_teams * 0.1)
    # Clamp: a tiny leaderboard can compute rank 0, and ranks must not invert.
    g = max(g, 1)
    s = max(s, g)
    b = max(b, s)
    return g, min(s, n_teams), min(b, n_teams)


def thresholds_from_leaderboard(
    scores: Sequence[float], greater_is_better: bool
) -> MedalThresholds:
    """Medal thresholds from a leaderboard's score distribution."""
    arr = np.sort(np.asarray(scores, dtype=float))
    if greater_is_better:
        arr = arr[::-1]  # best first
    n = arr.size
    g, s, b = medal_ranks(n)
    return MedalThresholds(
        gold=float(arr[g - 1]),
        silver=float(arr[s - 1]),
        bronze=float(arr[b - 1]),
        median=float(np.median(arr)),
        n_teams=n,
    )


def leaderboard_percentile(
    score: float, leaderboard: Sequence[float], greater_is_better: bool
) -> float:
    """Fraction of the leaderboard this score beats, in [0, 1].

    A raw score is not comparable across competitions: an AUC difference and an
    RMSE difference are different units pointing in opposite directions, and
    averaging them is meaningless. A percentile is comparable, direction-free
    and bounded -- which is why both teams who built a Kaggle-derived benchmark
    after MLE-bench (TML-bench, MLE-Dojo) replaced medal thresholds with a
    relative-position score rather than inherit raw-value transfer.
    """
    arr = np.asarray(leaderboard, dtype=float)
    if arr.size == 0:
        raise ValueError("empty leaderboard")
    beaten = (arr < score) if greater_is_better else (arr > score)
    return float(beaten.mean())


@dataclass
class GradingReport:
    """Upstream-compatible outcome for one submission."""

    competition_id: str
    submission_exists: bool = False
    valid_submission: bool = False
    score: float | None = None
    gold_medal: bool = False
    silver_medal: bool = False
    bronze_medal: bool = False
    above_median: bool = False
    thresholds: dict | None = None
    error: str | None = None

    @property
    def any_medal(self) -> bool:
        return self.gold_medal or self.silver_medal or self.bronze_medal

    def to_dict(self) -> dict:
        d = asdict(self)
        d["any_medal"] = self.any_medal
        return d


def read_submission(path: Path, id_column: str, target_column: str) -> dict[str, float]:
    """Parse a submission CSV into {id: prediction}.

    Raises :class:`InvalidSubmission` for every malformed shape rather than
    letting a bad file through as a zero score -- a malformed submission is an
    agent bug and must be reported as one, not as weak ML.
    """
    try:
        with path.open(newline="") as fh:
            reader = csv.DictReader(fh)
            if reader.fieldnames is None:
                raise InvalidSubmission("submission is empty")
            missing = {id_column, target_column} - set(reader.fieldnames)
            if missing:
                raise InvalidSubmission(
                    f"missing column(s) {sorted(missing)}; got {reader.fieldnames}"
                )
            out: dict[str, float] = {}
            for i, row in enumerate(reader, start=2):
                key = row[id_column]
                if key in out:
                    raise InvalidSubmission(f"duplicate id {key!r} on line {i}")
                raw = row[target_column]
                try:
                    out[key] = float(raw)
                except (TypeError, ValueError):
                    raise InvalidSubmission(
                        f"line {i}: {raw!r} is not a number"
                    ) from None
    except OSError as exc:
        raise InvalidSubmission(f"could not read submission: {exc}") from None
    if not out:
        raise InvalidSubmission("submission has a header but no rows")
    return out


def grade_submission(
    submission_path: str | Path, competition_dir: str | Path
) -> GradingReport:
    """Grade one submission. Never raises for anything the agent did."""
    comp_dir = Path(competition_dir)
    spec = json.loads((comp_dir / "competition.json").read_text())
    report = GradingReport(competition_id=spec["id"])

    sub_path = Path(submission_path)
    # Upstream scores a non-.csv path as "no submission", with only a warning.
    # Same rule here, but the reason is recorded rather than swallowed.
    if sub_path.suffix.lower() != ".csv":
        report.error = f"submission path is not a .csv: {sub_path.name}"
        return report
    if not sub_path.is_file():
        report.error = "no submission file"
        return report
    report.submission_exists = True

    answers = json.loads((comp_dir / "prepared" / "private" / "answers.json").read_text())
    metric = get_metric(spec["metric"])
    try:
        preds = read_submission(sub_path, spec["id_column"], spec["target_column"])
        missing = set(answers) - set(preds)
        if missing:
            raise InvalidSubmission(
                f"{len(missing)} id(s) missing, e.g. {sorted(missing)[:3]}"
            )
        extra = set(preds) - set(answers)
        if extra:
            raise InvalidSubmission(
                f"{len(extra)} unknown id(s), e.g. {sorted(extra)[:3]}"
            )
        ids = sorted(answers)
        y_true = np.array([answers[i] for i in ids], dtype=float)
        y_pred = np.array([preds[i] for i in ids], dtype=float)
        score = metric(y_true, y_pred)
    except InvalidSubmission as exc:
        report.error = str(exc)
        return report

    report.valid_submission = True
    # Upstream's Grader.__call__ returns round(score, 5). Matching it exactly is
    # what makes a score here directly comparable to a published MLE-bench
    # number, and it is not a cosmetic detail: upstream's own Known Issues flag
    # three competitions whose leaderboards are dense enough that a fifth-decimal
    # difference can move a medal.
    report.score = round(score, UPSTREAM_SCORE_DECIMALS)
    t = MedalThresholds(**spec["thresholds"])
    report.thresholds = spec["thresholds"]
    gib = metric.greater_is_better
    report.gold_medal = t.beats(score, gib, t.gold)
    report.silver_medal = t.beats(score, gib, t.silver)
    report.bronze_medal = t.beats(score, gib, t.bronze)
    report.above_median = t.beats(score, gib, t.median)
    return report


def grade_jsonl(
    jsonl_path: str | Path, competitions_root: str | Path
) -> list[GradingReport]:
    """Grade every row of the JSONL the harness emits."""
    root = Path(competitions_root)
    reports = []
    for line in Path(jsonl_path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "//")):
            continue  # upstream skips these too
        row = json.loads(line)
        reports.append(
            grade_submission(row["submission_path"], root / row["competition_id"])
        )
    return reports


__all__ = [
    "GradingReport",
    "UPSTREAM_SCORE_DECIMALS",
    "MedalThresholds",
    "grade_jsonl",
    "grade_submission",
    "medal_ranks",
    "read_submission",
    "thresholds_from_leaderboard",
]
